import express from "express";
import path from "path";
import { createServer as createViteServer } from "vite";
import { GoogleGenAI } from "@google/genai";
import fs from "fs";
import dotenv from "dotenv";
import admin from "firebase-admin";
import { getFirestore } from "firebase-admin/firestore";

dotenv.config();

// Load Firebase Config for databaseId
let firestoreDatabaseId: string | undefined;
try {
  const config = JSON.parse(fs.readFileSync("./firebase-applet-config.json", "utf-8"));
  firestoreDatabaseId = config.firestoreDatabaseId;
  console.log(`Using Firestore database ID: ${firestoreDatabaseId || "(default)"}`);
} catch (err) {
  console.warn("Could not read firebase-applet-config.json for databaseId");
}

// Smart Router Logic
enum TaskType {
  SIMPLE_EXTRACTION = "simple_extraction",
  COMPLEX_REASONING = "complex_reasoning",
  LEGAL_GROUNDING = "legal_grounding"
}

function getBestModel(task: TaskType): string {
  switch (task) {
    case TaskType.SIMPLE_EXTRACTION:
      return "gemini-2.0-flash";
    case TaskType.COMPLEX_REASONING:
    case TaskType.LEGAL_GROUNDING:
      return "gemini-3.1-pro-preview";
    default:
      return "gemini-3-flash-preview";
  }
}

function detectTaskType(payload: any): TaskType {
  const text = JSON.stringify(payload).toLowerCase();
  
  if (text.includes("search") || text.includes("statute") || text.includes("ors ") || text.includes("constitution")) {
    return TaskType.LEGAL_GROUNDING;
  }
  
  if (text.includes("analyze") || text.includes("discrepancy") || text.includes("contradiction") || text.includes("misconduct") || text.includes("violation")) {
    return TaskType.COMPLEX_REASONING;
  }
  
  return TaskType.SIMPLE_EXTRACTION;
}

// Initialize Firebase Admin
let adminApp: admin.app.App | null = null;
try {
  const serviceAccount = process.env.FIREBASE_SERVICE_ACCOUNT_JSON 
    ? JSON.parse(process.env.FIREBASE_SERVICE_ACCOUNT_JSON) 
    : null;

  if (serviceAccount) {
    adminApp = admin.initializeApp({
      credential: admin.credential.cert(serviceAccount)
    });
    console.log("Firebase Admin initialized");
  } else {
    console.warn("FIREBASE_SERVICE_ACCOUNT_JSON not found, backend auth disabled");
  }
} catch (err) {
  console.error("Firebase Admin init error:", err);
}

const firestore = adminApp 
  ? (firestoreDatabaseId ? getFirestore(adminApp, firestoreDatabaseId) : getFirestore(adminApp)) 
  : null;

const ai = new GoogleGenAI({
  apiKey: process.env.GEMINI_API_KEY || process.env.GOOGLE_API_KEY || "",
  httpOptions: {
    headers: {
      'User-Agent': 'aistudio-build',
    }
  }
});

async function startServer() {
  const app = express();
  const PORT = 3000;

  app.use(express.json({ limit: '50mb' }));

  // API Routes
  app.get("/api/health", (req, res) => {
    res.json({ 
      status: "ok", 
      firebase: !!adminApp, 
      gemini: !!process.env.GEMINI_API_KEY
    });
  });

  // Advanced Forensic Analysis & Cross-Referencing
  app.post("/api/analyze-encounter", async (req, res) => {
    try {
      const { transcript, officerStatement, caseInfo } = req.body;
      const taskType = detectTaskType(req.body);
      const model = getBestModel(taskType);
      
      console.log(`Smart Router: Selected ${model} for ${taskType}`);

      const response = await ai.models.generateContent({ 
        model,
        contents: `Analyze this case as an independent technology service for the legal industry.
      
      CASE INFO: ${JSON.stringify(caseInfo)}
      
      OFFICER STATEMENT:
      """
      ${officerStatement || "No statement provided for cross-ref."}
      """
      
      TRANSCRIPT:
      """
      ${transcript}
      """
      
      Respond only in structured JSON matching the requested schema.`,
        config: {
          tools: taskType === TaskType.LEGAL_GROUNDING ? [{ googleSearch: {} }] : undefined,
          systemInstruction: `You are a Senior Forensic Internal Affairs Investigator and Legal Expert for the Oregon DOJ.
        Your task is to perform a deep-dive analysis of a police encounter for an independent technology platform.
        
        CRITICAL OPERATING PROTOCOLS (UPL COMPLIANCE):
        1. YOU ARE NOT AN ATTORNEY. This output is for INFORMATIONAL PURPOSES ONLY.
        2. NO ATTORNEY-CLIENT RELATIONSHIP IS ESTABLISHED.
        3. DO NOT give specific "legal advice" (e.g., "you should file this motion"). Instead, "identify potential discrepancies" or "spot constitutional issues for review by counsel".
        4. MANDATORY DISCLAIMER: Every summary or report MUST conclude with: "NOTICE: This analysis was generated by an automated technology service. It does not constitute legal advice or establish an attorney-client relationship. All findings must be reviewed by qualified legal counsel."
        
        INPUTS:
        1. Video Transcript (Timestamped)
        2. Officer's Written Statement
        3. Case Context (Jurisdiction: Oregon)
        
        GOALS:
        - EXTRACT key events with precise timestamps (HH:MM:SS).
        - CROSS-REFERENCE: Identify every instance where the Officer's Statement contradicts the Video Transcript.
        - MISCONDUCT DETECTION: Flags specific instances of:
          - Unlawful use of force
          - Constitutional violations (Search/Seizure/Self-incrimination)
          - Procedural errors (Miranda, ORS 810.410 violations)
          - Deceit: Conscious misreporting of events.
        
        OUTPUT SCHEMA (JSON):
        {
          "events": [{ "time": "HH:MM:SS", "type": "search|encounter|seizure|verbal|use_of_force|miranda|contradiction", "description": "string", "severity": "low|medium|high|critical" }],
          "violations": [{ "type": "string", "statute": "string", "description": "string", "severity": "critical" }],
          "contradictions": [{ "timestamp": "HH:MM:SS", "statement": "string", "reality": "string", "legal_impact": "string" }],
          "summary": "Professional executive summary of misconduct potential."
        }
        
        Always cite Oregon Revised Statutes (ORS) and Article I of the Oregon Constitution.`,
        }
      });

      const text = response.text || "{}";
      const cleanJson = text.replace(/```json|```/g, "").trim();
      res.json(JSON.parse(cleanJson));
    } catch (error: any) {
      console.error("Forensic Analysis Error:", error);
      res.status(500).json({ error: "Failed to process forensic request: " + error.message });
    }
  });

  // Legal Analysis & Search with Grounding
  app.post("/api/legal-chat", async (req, res) => {
    try {
      const { message, history } = req.body;
      const taskType = TaskType.LEGAL_GROUNDING;
      const model = getBestModel(taskType);

      console.log(`Smart Router: Selected ${model} for ${taskType}`);
      
      const chat = ai.chats.create({
        model,
        config: {
          systemInstruction: `You are a specialized Oregon Constitutional & Forensic Legal Assistant for an independent technology service. 
          Your goal is to provide accurate citations to Oregon Revised Statutes (ORS), the Oregon Constitution (Article I), 
          and relevant Oregon Case Law (e.g., State v. Arreola, State v. Backstrand).
          
          CRITICAL UPL PROTOCOLS:
          - You are a TECHNOLOGY SERVICE, not an attorney.
          - No attorney-client relationship is created.
          - Informational purposes only.
          - You MUST include a disclaimer at the end of every response stating that this is not legal advice.
          
          Always prioritize Article I Section 9 (Seizures/Searches) and Section 12 (Self-incrimination) when analyzing police encounters.
          Use Google Search to verify the CURRENCY of statutes as the Oregon legislature often updates ORS.
          If you find a contradiction between an officer's statement and a statute, highlight it clearly.`,
          tools: [{ googleSearch: {} }],
        },
        history: history || [],
      });

      const response = await chat.sendMessage({ message });
      
      // Extract grounding metadata for the UI if available
      const sources = response.candidates?.[0]?.groundingMetadata?.groundingChunks?.map((chunk: any) => ({
        title: chunk.web?.title || "Legal Source",
        url: chunk.web?.uri || "#"
      })).filter((s: any) => s.url !== "#") || [];

      res.json({ 
        text: response.text,
        sources 
      });
    } catch (error: any) {
      console.error("Legal Chat Error:", error);
      res.status(500).json({ error: error.message });
    }
  });

  // Vite middleware for development
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), 'dist');
    app.use(express.static(distPath));
    app.get('*', (req, res) => {
      res.sendFile(path.join(distPath, 'index.html'));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`JurisLens Server running on http://localhost:${PORT}`);
  });
}

startServer().catch(err => {
  console.error("Failed to start server:", err);
});
