import React from 'react';

export function LegalFooter() {
  return (
    <footer className="w-full bg-[#050505] border-t border-[#1F1F1F] py-8 px-8 font-sans">
      <div className="max-w-7xl mx-auto flex flex-col md:flex-row justify-between gap-8">
        <div className="max-w-md">
          <p className="text-[10px] text-[#444444] font-bold uppercase tracking-widest mb-4">
            Legal Disclaimer & Terms of Service
          </p>
          <p className="text-[#8E8E8E] text-[11px] leading-relaxed font-medium">
            JurisLens is a technology-driven forensic analysis platform. We are not a law firm and do not provide legal advice, legal services, or legal representation. 
            Use of this platform does not establish an attorney-client relationship. All analysis, reports, and insights generated by the system are for informational 
            purposes only and must be reviewed by qualified legal counsel prior to use in any legal proceeding.
          </p>
        </div>
        
        <div className="flex flex-wrap gap-8 md:gap-16">
          <div className="space-y-4">
            <h4 className="text-[9px] text-[#FF4F00] font-bold uppercase tracking-widest">Compliance</h4>
            <div className="space-y-2">
              <p className="text-[10px] text-white font-semibold">UPL Protocol Alpha-6</p>
              <p className="text-[10px] text-[#444444] font-medium leading-tight max-w-[200px]">
                Strict enforcement of Unauthorized Practice of Law protocols. Continuous auditing enabled.
              </p>
            </div>
          </div>
          
          <div className="space-y-4">
            <h4 className="text-[9px] text-[#FF4F00] font-bold uppercase tracking-widest">System Status</h4>
            <div className="space-y-2">
              <p className="text-[10px] text-white font-semibold flex items-center gap-2">
                <span className="w-1.5 h-1.5 bg-green-500 rounded-full animate-pulse" />
                Forensic Engine Active
              </p>
              <p className="text-[10px] text-[#444444] font-medium">Independent Technology Service</p>
            </div>
          </div>
        </div>
      </div>
      
      <div className="max-w-7xl mx-auto mt-8 pt-8 border-t border-[#141414] flex flex-col sm:flex-row justify-between items-center gap-4">
        <p className="text-[9px] text-[#222222] font-bold uppercase tracking-[0.3em]">
          © 2026 JurisLens Forensic Systems. No Affiliation with external law firms.
        </p>
        <div className="flex gap-4">
          <button className="text-[9px] text-[#444444] font-bold uppercase tracking-widest hover:text-white transition-colors">Privacy</button>
          <button className="text-[9px] text-[#444444] font-bold uppercase tracking-widest hover:text-white transition-colors">Terms</button>
          <button className="text-[9px] text-[#444444] font-bold uppercase tracking-widest hover:text-white transition-colors">Ethics</button>
        </div>
      </div>
    </footer>
  );
}
